name: daniu_weather_back
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-266.8.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_weather_bg: ^2.8.2
  qweather_icons: ^1.6.0
  dio: ^5.3.3
  ionicons: ^0.2.2
  flutter_bloc: ^7.0.0
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.11
  vibration: ^1.8.4


flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/citycode.json

#  D:\SDK\flutter2\bin\flutter.bat  build apk --split-per-abi --no-sound-null-safety
